//
//  MessagesViewController.swift
//  DeckedOut MessagesExtension
//
//  Created by Sawyer Christensen on 6/19/25.
//

import UIKit
import Messages
import SwiftUI

class MessagesViewController: MSMessagesAppViewController {
    
    //Le Game Engine
    let gameManager = GameManager()

    // MARK: – View Life-Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Listen for turn completion
        gameManager.onTurnCompleted = { [weak self] gameState in
            self?.sendGameMove(gameState: gameState)
        }
    }

    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        super.willBecomeActive(with: conversation)
        decodeMessage(from: conversation)
        requestPresentationStyle(.expanded)
        presentGameController()
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dismisses the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
        
        
    }
    
    override func didSelect(_ message: MSMessage, conversation: MSConversation) {
        // Called when a user selects a message when the app is already running (like in compact view)
        super.didSelect(message, conversation: conversation)
        print("didSelect")
        decodeMessage(from: conversation)
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device. <- this is questionable. it appears to trigger when a message is sent too
        
        // Use this method to trigger UI updates in response to the message. ^^
        print("didReceive")
        decodeMessage(from: conversation)
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }
    
    // MARK: - Helper functions
    
    /*private func presentMenuController(for presentationStyle: MSMessagesAppPresentationStyle, with conversation: MSConversation) {
        let viewModel = MenuViewModel(presentationStyle: presentationStyle)
        self.menuViewModel = viewModel
        
        let menuView = MessagesMainMenuView(viewModel: viewModel) { [weak self] in
            self?.createGame(conversation: conversation)
        }
                
        presentView(UIHostingController(rootView: menuView))
    }*/
    
    private func presentGameController() {
        //print("presentGameController")
        //removeAllChildViewControllers()
        let gameRootView = GinRootView(game: self.gameManager)
        let gameController = UIHostingController(rootView: gameRootView)
        
        presentView(gameController)
    }
    
    private func presentView(_ viewController: UIViewController) {
        //dismiss any pop-up (like the promotion window) that might be open
        dismiss(animated: false) { [weak self] in
            guard let self = self else { return }
            
            //remove all existing child view controllers
            for child in self.children {
                child.willMove(toParent: nil)
                child.view.removeFromSuperview()
                child.removeFromParent()
            }
            
            //add the new view controller
            self.addChild(viewController)
            viewController.view.frame = self.view.bounds
            viewController.view.translatesAutoresizingMaskIntoConstraints = false
            self.view.addSubview(viewController.view)
            
            NSLayoutConstraint.activate([
                viewController.view.topAnchor.constraint(equalTo: self.view.topAnchor),
                viewController.view.bottomAnchor.constraint(equalTo: self.view.bottomAnchor),
                viewController.view.leadingAnchor.constraint(equalTo: self.view.leadingAnchor),
                viewController.view.trailingAnchor.constraint(equalTo: self.view.trailingAnchor)
            ])
            
            viewController.didMove(toParent: self)
        }
    }
    
    func sendGameMove(gameState: GameState) {
        print("sending game state...")
        guard let conversation = activeConversation else { return }
        guard let jsonData = try? JSONEncoder().encode(gameState) else { return }
        
        // Package the game state further
        let jsonString = jsonData.base64EncodedString()
        var components = URLComponents()
        components.queryItems = [URLQueryItem(name: "gameState", value: jsonString)]
        
        // Create the message & attach data
        let message = MSMessage(session: conversation.selectedMessage?.session ?? MSSession())
        message.url = components.url
        
        // Message Appearance
        let layout = MSMessageTemplateLayout()
        layout.caption = "Your Turn!"
        layout.subcaption = "I just discarded."
        message.layout = layout
        
        // ...aaaand send!
        conversation.send(message) { error in
            if let error = error { print(error) }
        }
    }
    
    private func decodeMessage(from conversation: MSConversation) {
        guard let message = conversation.selectedMessage,
              let url = message.url,
              let components = URLComponents(url: url, resolvingAgainstBaseURL: false),
              let queryItems = components.queryItems,
              let stateItem = queryItems.first(where: { $0.name == "gameState" }),
              let stateString = stateItem.value,
              let stateData = Data(base64Encoded: stateString),
              let loadedState = try? JSONDecoder().decode(GameState.self, from: stateData)
        else {
            // If any step fails (e.g., this is a new conversation with no history),
            // we just return and let the default "New Game" state stand.
            print("Failed to decode the recieved message")
            return
        }
        
        gameManager.loadState(loadedState)
    }

}
