//
//  MessagesViewController.swift
//  DeckedOut MessagesExtension
//
//  Created by Sawyer Christensen on 6/19/25.
//

import UIKit
import Messages

class MessagesViewController: MSMessagesAppViewController {

    // MARK: - Properties
    private var deck = Deck()
    private let label = UILabel()
    private let cardImageView = UIImageView()

    // MARK: - View Life-Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        deck.shuffle()

        configureLabel()
        configureImageView()
        configureDrawButton()
        layoutUI()
    }

    // MARK: - UI Setup
    private func configureLabel() {
        label.text = "Tap to draw a card"
        label.font = UIFont.systemFont(ofSize: 20, weight: .medium)
        label.textColor = .darkGray
        label.textAlignment = .center
        label.translatesAutoresizingMaskIntoConstraints = false
    }

    private func configureImageView() {
        cardImageView.contentMode = .scaleAspectFit
        cardImageView.translatesAutoresizingMaskIntoConstraints = false
    }

    private func configureDrawButton() {
        let button = UIButton(type: .system)
        button.setTitle("Draw Card", for: .normal)
        button.titleLabel?.font = UIFont.systemFont(ofSize: 20, weight: .medium)
        button.addTarget(self, action: #selector(drawCard), for: .touchUpInside)
        button.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(button)

        // Button constraints
        NSLayoutConstraint.activate([
            button.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            button.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -20)
        ])
    }

    private func layoutUI() {
        view.addSubview(label)
        view.addSubview(cardImageView)

        NSLayoutConstraint.activate([
            cardImageView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            cardImageView.centerYAnchor.constraint(equalTo: view.centerYAnchor, constant: -30),
            cardImageView.widthAnchor.constraint(equalToConstant: 80),
            cardImageView.heightAnchor.constraint(equalToConstant: 120),

            label.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            label.topAnchor.constraint(equalTo: cardImageView.bottomAnchor, constant: 10)
        ])
    }

    // MARK: - Actions
    @objc private func drawCard() {
        if let card = deck.drawCard() {
            // Build the asset name directly from your new enums
            let imageName = "\(card.rank.rawValue)\(card.suit.rawValue)"   // e.g., "7Hearts", "QSpades"
            cardImageView.image = UIImage(named: imageName)
            label.text = imageName                                           // optional debug text
        } else {
            cardImageView.image = nil
            label.text = "No cards left!"
        }
    }

    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dismisses the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

}
